// <auto-generated />
using Avakado.Services.CouponApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avakado.Services.CouponApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241125125915_CouponTables")]
    partial class CouponTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Avakado.Services.CouponApi.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouponCode = "KOD1",
                            DiscountAmount = 10.0,
                            MinAmount = 50
                        },
                        new
                        {
                            Id = 2,
                            CouponCode = "KOD2",
                            DiscountAmount = 15.0,
                            MinAmount = 100
                        },
                        new
                        {
                            Id = 3,
                            CouponCode = "KOD3",
                            DiscountAmount = 20.0,
                            MinAmount = 150
                        },
                        new
                        {
                            Id = 4,
                            CouponCode = "KOD4",
                            DiscountAmount = 25.0,
                            MinAmount = 200
                        },
                        new
                        {
                            Id = 5,
                            CouponCode = "KOD5",
                            DiscountAmount = 30.0,
                            MinAmount = 250
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
